<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Contract.proto

namespace Geo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request
 *
 * Generated from protobuf message <code>geo.GetGeolocationRequest</code>
 */
class GetGeolocationRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Street = 1;</code>
     */
    protected $Street = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Street
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Contract::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string Street = 1;</code>
     * @return string
     */
    public function getStreet()
    {
        return $this->Street;
    }

    /**
     * Generated from protobuf field <code>string Street = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStreet($var)
    {
        GPBUtil::checkString($var, True);
        $this->Street = $var;

        return $this;
    }

}

