<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Contract.proto

namespace Geo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Response
 *
 * Generated from protobuf message <code>geo.GetGeolocationReply</code>
 */
class GetGeolocationReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.geo.Location Location = 1;</code>
     */
    protected $Location = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Geo\Location $Location
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Contract::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.geo.Location Location = 1;</code>
     * @return \Geo\Location
     */
    public function getLocation()
    {
        return $this->Location;
    }

    /**
     * Generated from protobuf field <code>.geo.Location Location = 1;</code>
     * @param \Geo\Location $var
     * @return $this
     */
    public function setLocation($var)
    {
        GPBUtil::checkMessage($var, \Geo\Location::class);
        $this->Location = $var;

        return $this;
    }

}

