version: "2.0"

services:
  nginx:
    container_name: delivery_nginx
    image: nginx:1.21.6
    ports:
      - "8082:80"
    volumes:
      - "./../:/var/www"
      - "./../docker/nginx/config:/etc/nginx/conf.d"
      - "./../docker/nginx/include:/etc/nginx/include"
    links:
      - php
  php:
    container_name: delivery_php
    build: "./php"
    volumes:
      - "./../:/var/www"
    depends_on:
      - db
    links:
      - db
      - db-test

  db:
    container_name: delivery_db
    image: postgres:latest
    ports:
      - 5438:5432
    environment:
      - POSTGRES_USER=delivery
      - POSTGRES_PASSWORD=delivery
    volumes:
      - "./../docker/mount/postgres:/var/lib/postgresql/data"

  db-test:
    container_name: delivery_db_test
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=delivery
      - POSTGRES_PASSWORD=delivery
    volumes:
      - "./../docker/mount/postgres-test:/var/lib/postgresql/data"