<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Contract.proto

namespace GPBMetadata;

class Contract
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8e020a0e436f6e74726163742e70726f746f120367656f22270a154765" .
            "7447656f6c6f636174696f6e52657175657374120e0a0653747265657418" .
            "012001280922360a1347657447656f6c6f636174696f6e5265706c79121f" .
            "0a084c6f636174696f6e18012001280b320d2e67656f2e4c6f636174696f" .
            "6e22200a084c6f636174696f6e12090a017818012001280512090a017918" .
            "0220012805221d0a0d4572726f72526573706f6e7365120c0a0474657874" .
            "180120012809324d0a0347656f12460a0e47657447656f6c6f636174696f" .
            "6e121a2e67656f2e47657447656f6c6f636174696f6e526571756573741a" .
            "182e67656f2e47657447656f6c6f636174696f6e5265706c79620670726f" .
            "746f33"
        ), true);

        static::$is_initialized = true;
    }
}

