<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Contract.proto

namespace GPBMetadata;

class Contract
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a85020a0e436f6e74726163742e70726f746f22270a1547657447656f6c" .
            "6f636174696f6e52657175657374120e0a06537472656574180120012809" .
            "22320a1347657447656f6c6f636174696f6e5265706c79121b0a084c6f63" .
            "6174696f6e18012001280b32092e4c6f636174696f6e22200a084c6f6361" .
            "74696f6e12090a017818012001280512090a0179180220012805221d0a0d" .
            "4572726f72526573706f6e7365120c0a047465787418012001280932450a" .
            "0347656f123e0a0e47657447656f6c6f636174696f6e12162e4765744765" .
            "6f6c6f636174696f6e526571756573741a142e47657447656f6c6f636174" .
            "696f6e5265706c794206ca020347656f620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

